### ISSUE TITLE
버튼을 누르면 추천순별로 정렬시켜 표시

### ISSUE THREAD

**Issue by FineScore** [GA-Team2/burang-narang#11]
**구현 목적**
인기 플랜 정보를 전달할 페이지이기 때문에 게시판 목록에도 추천 순으로 정렬할 수 있는 기능이 필요하다고 생각

**구현할 기능**
- "추천 순으로 표시" 버튼 추가
- 버튼 클릭하면 추천 수 기준 내림차순으로 정렬하여 목록 표시

**Comment by Seung9-Kang** [comment]
역시 게시글은 추천순이죠 좋은 생각 같아요
